
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine


# Copy the custom Nginx configuration we just made
COPY nginx.conf /etc/nginx/conf.d/default.conf


# Copy the built React files from Stage 1 into Nginx's serving directory
COPY --from=build /app/dist /usr/share/nginx/html


EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]